name: Release on tag

on:
  workflow_call:
    inputs:
      desired_tag:
        required: false
        type: string
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-tags: true

      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-tags: true
          ref: ${{ inputs.desired_tag }}
        if: inputs.desired_tag != ''

      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ inputs.desired_tag == '' && github.ref_name || inputs.desired_tag }}
          includeInvalidCommits: true
          excludeTypes:

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          makeLatest: true
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          skipIfReleaseExists: true
          allowUpdates: true
          updateOnlyUnreleased: true
          draft: false

      - name: Build and Deploy to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: shanemcc/docker-exabgp
          tags: ${{ github.ref_name }},latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Deploy to GHCR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: docker-exabgp
          tags: ${{ github.ref_name }},latest
          dockerfile: Dockerfile
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Deploy to registry
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: public/docker-exabgp
          tags: ${{ github.ref_name }},latest
          dockerfile: Dockerfile
          registry: registry.shanemcc.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
